appName = "gochat"

[log]
level = "debug"
path = "logs"

[mysql]
host = "127.0.0.1"
name = "gochat"
password = "Test_2025"
port = 3306
tablePrefix = ""
user = "root"
timeout = "10s"

[api]
host = "127.0.0.1"
port = 8083
prefix = "/api/v1"

[jwt]
secret = "shy-robin"
expireTime = 24 # 单位: 小时
