definitions:
  common.BadRequestResponse:
    properties:
      message:
        example: 参数错误
        type: string
      status:
        example: error
        type: string
    type: object
  common.UnauthorizedResponse:
    properties:
      message:
        example: 鉴权失败
        type: string
      status:
        example: error
        type: string
    type: object
  dto.CreateUserRequest:
    properties:
      avatar:
        example: https://avatars.githubusercontent.com/u/123456?v=4
        type: string
      email:
        example: robin@qq.com
        type: string
      nickname:
        example: robin
        type: string
      password:
        example: "123456"
        minLength: 8
        type: string
      username:
        example: robin
        maxLength: 20
        minLength: 2
        type: string
    required:
    - password
    - username
    type: object
  dto.CreateUserResponse:
    properties:
      data:
        $ref: '#/definitions/dto.CreateUserResponseData'
      status:
        example: success
        type: string
    type: object
  dto.CreateUserResponseData:
    properties:
      createAt:
        description: 可能需要格式化为字符串
        example: 2025-11-23T15:53:56.811
        type: string
      username:
        description: '注意: 响应中不包含 PasswordHash'
        example: robin
        type: string
      uuid:
        example: db376853-8f93-41f9-9a44-3c5ad8eedbbb
        type: string
    type: object
  dto.GetUserInfoData:
    properties:
      avatar:
        example: https://avatars.githubusercontent.com/u/123456?v=4
        type: string
      email:
        example: robin@test.com
        type: string
      nickname:
        example: robin
        type: string
      username:
        example: robin
        type: string
      uuid:
        example: db376853-8f93-41f9-9a44-3c5ad8eedbbb
        type: string
    type: object
  dto.GetUserInfoResponse:
    properties:
      data:
        $ref: '#/definitions/dto.GetUserInfoData'
      status:
        example: success
        type: string
    type: object
  dto.LoginRequest:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: robin
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginResponse:
    properties:
      data:
        $ref: '#/definitions/dto.LoginResponseData'
      status:
        example: success
        type: string
    type: object
  dto.LoginResponseData:
    properties:
      expireAt:
        example: 1763910483465
        type: integer
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnb2NoYXQtYXBpLXNlcnZpY2UiLCJleHAiOjE3NjM5OTc1MTksImlhdCI6MTc2MzkxMTExOSwidXNlcklkIjoiY2YzZDE1ZmMtM2ZlYS00NDkzLWFjMDMtYzBiMjkzYTBjNjc4IiwidXNlcm5hbWUiOiJyb2JpbjYifQ.Rddl8mxWIPBWYCIO5TQYTG8uvyyPbP3FF9ozGdfytwg
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Swagger API docs for the GoChat API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GoChat Swagger API
  version: "1.0"
paths:
  /sessions:
    post:
      consumes:
      - application/json
      description: 传入参数，用户登录
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 登录成功
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/common.BadRequestResponse'
      summary: 用户登录
      tags:
      - users
  /users:
    post:
      consumes:
      - application/json
      description: 传入参数，注册用户
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功
          schema:
            $ref: '#/definitions/dto.CreateUserResponse'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/common.BadRequestResponse'
      summary: 注册用户
      tags:
      - users
  /users/:id:
    get:
      consumes:
      - application/json
      description: 传入参数，获取用户信息
      produces:
      - application/json
      responses:
        "201":
          description: 获取成功
          schema:
            $ref: '#/definitions/dto.GetUserInfoResponse'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/common.BadRequestResponse'
        "401":
          description: 鉴权失败
          schema:
            $ref: '#/definitions/common.UnauthorizedResponse'
      summary: 获取用户信息
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      description: 传入参数，获取当前用户信息
      produces:
      - application/json
      responses:
        "201":
          description: 获取成功
          schema:
            $ref: '#/definitions/dto.GetUserInfoResponse'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/common.BadRequestResponse'
        "401":
          description: 鉴权失败
          schema:
            $ref: '#/definitions/common.UnauthorizedResponse'
      summary: 获取当前用户信息
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
